### PR TITLE
Implement halo text for reading journal

### PR DESCRIPTION
**Pull request by MassCraxx**
I thought it would be nice to have the same halo text when reading the book.
You probably had that planned anyway, thought maybe you are busy so I just went ahead.

I also tried fixing the halo displaying "PlantScavenging" instead of Foraging but could not make that work. This could also be the reason why some users had translation issues, since the string "IGUI_perks_" only exists for Foraging. It has something to do with using the perk type for the string instead of the perk name, but nothing I tried instead seemed consistent for all skills...

Love the progress this mod made, thanks dude. Cheers

On a sidenote: Looking forward to your response to Lucas on the workshop. Would love to learn how to get some typecast or autocompletion on a proper lua IDE. I'm just using VS Code.

### CODE REVIEW

**Comment by ChuckTheSheep** [comment]
I probably need to redo the halo text stuff as it has a habit of stacking multiple concated phrases together.

As for the autofill stuff try this- https://github.com/Konijima/PZ-Libraries

**Comment by MassCraxx** [comment]
Ah ok, yeah I also thought it might get called too often, but works well so far and I really like the idea!

Thanks for the autofill pointer, very helpful!

**Comment by MassCraxx** [comment]
Sorry going Off-Topic here: Nice tutorial on how to include global libraries, but any pointers on how to get the actual pz source as a .jar lib? I am not very experienced with decompilers...

**Comment by ChuckTheSheep** [comment]
I use the cocolabs tool but it's outdated I believe (?).

**Review by ChuckTheSheep — APPROVED** [review]
Add halo text for reading. Thanks to MassCraxx,

**Pull request merged**
